### ISSUE TITLE
CI/CD jobs fail waiting for Kubernetes pods

### ISSUE THREAD

**Issue by xbrianh** [DataBiosphere/bdcat-integration-tests#44]
This appears to occur semi-regularly for [featured-notebooks](https://github.com/DataBiosphere/featured-notebooks) tests. When it does occur, CI/CD is not useful. This problem may also cause spurious failures for BioData Catalyst integration tests.

![image](https://user-images.githubusercontent.com/32105697/107421272-fd4a9080-6ad6-11eb-9e7a-6da377984966.png)

**Comment by DailyDreaming** [comment]
This is a gitlab issue and not an integration test issue.  Ticket for reference: https://ucsc-cgl.atlassian.net/browse/TLP-1890

**Comment by DailyDreaming** [comment]
Closing as a duplicate ticket.
