### ISSUE TITLE
Credentials stored in GitLab CI/CD environment variables should be masked

### ISSUE THREAD

**Issue by xbrianh** [DataBiosphere/bdcat-integration-tests#45]
This helps prevents credentials from being displayed in job logs. Read all about masking [here](https://docs.gitlab.com/ee/ci/variables/#create-a-custom-variable-in-the-ui).

**Comment by DailyDreaming** [comment]
Removing as a duplicate of https://ucsc-cgl.atlassian.net/browse/TLP-1892 .
