### ISSUE TITLE
test_pfb_handoff_from_gen3_to_terra not resilient to transient errors, can delete workspace too soon

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/bdcat-integration-tests#93]
The [test_pfb_handoff_from_gen3_to_terra](https://github.com/DataBiosphere/bdcat-integration-tests/blob/a3c1ab79d97010fa19b0402b8d6f6a332274341d/test/test_basic_submission.py#L156) test creates a Terra workspace, imports a static PFB to that workspace, loops/waits until the import's status is done or error, then deletes the Terra workspace.

The loop in which this test queries for the import job's status - [link](https://github.com/DataBiosphere/bdcat-integration-tests/blob/a3c1ab79d97010fa19b0402b8d6f6a332274341d/test/test_basic_submission.py#L170-L178) - is not resilient to transient errors such as a network blip. If any of these status requests returns non-200, or returns some response body other than what is expected, the test will break out of this loop. It will then delete the workspace.

In the case of a transient error, the import may still be running - but, by deleting the workspace, the import will necessarily fail. Perhaps it would be better to allow for transient errors and not immediately move to deleting the workspace.

Side note #1: perhaps also change the [name of the workspace used for this test](https://github.com/DataBiosphere/bdcat-integration-tests/blob/a3c1ab79d97010fa19b0402b8d6f6a332274341d/test/test_basic_submission.py#L158)? `drs_test_{time_stamp}_delete_me` is misleading and adds difficulty when debugging test failures.

Side note #2: this test's behavior exposed a Terra bug, in which a still-running import job whose workspace is deleted causes multiple retries of that job, all of which will fail. Terra will fix this issue! If you hear about this problem, know that it's on us and we'll address it.

**Comment by DailyDreaming** [comment]
@davidangb The loop mentioned should be resilient to transient network blips (500, 502, 503, 504) and retry for a short period of time (second interval defaults before giving up are: [1, 1, 2, 4, 8]): https://github.com/DataBiosphere/bdcat-integration-tests/blob/a71c5cd99a1b764fe99c82399b62ae4129707a38/test/utils.py#L273

If you have other error codes you feel should be added, please let me know.  Or if the retry interval times should be extended.

Responding to side-note 1: I support making the test name more descriptive (and will create a PR to that effect), but the unique time stamp prevents tests from attempting to use the same workspace, which can result in a 409 conflict when creating the workspace, or attempts to use the workspace of a test that was triggered independently.  So I would like to keep the time stamp.

Side note 2:  Thank you!

**Comment by davidangb** [comment]
interesting! Thanks for the clarification on the request retries.

The context for all this is that we have been debugging the Terra issues from side note 2. We're seeing that we somewhat regularly - once every few weeks - have "stuck" import jobs from this test. The error messages inside Terra mention the workspace name … which, because it mentioned "drs_test", caused some confusion.  The symptom we see is that the workspace in question is deleted but the import job keeps running, which then fails. I can see that the delete-workspace calls from this test do happen. 

So maybe it's not an http response code problem or connection error, maybe somehow Terra is returning some json the test doesn't expect? I'm not sure what's going wrong, just that we see the workspace being deleted prematurely. I'll keep digging in on our end too.

**Comment by DailyDreaming** [comment]
@davidangb Thanks!  Very curious if it's an extended network error or something else.  I'll watch this issue for updates.

In the meantime, I have two minor PRs to help if you have time to take a look:

https://github.com/DataBiosphere/bdcat-integration-tests/pull/94
https://github.com/DataBiosphere/bdcat-integration-tests/pull/95

**Comment by davidangb** [comment]
approved both! Thanks for the quick turnaround on those.

**Comment by DailyDreaming** [comment]
@davidangb Thanks for the reviews!

**Comment by davidangb** [comment]
we just ran into the issue again with workspace broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me, if that's helpful. I am looking into it from Terra's end too.

**Comment by davidangb** [comment]
Here's the annotated sequence of events as I see them:

workspace is created, then the import job is started. Both are successful:
```
April 29th 2022, 15:07:16.195	[INFO] [19:07:16.195] [scala-execution-context-global-32846] o.b.d.r.workspace.WorkspaceService - createWorkspace - workspace:'integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me' - UUID:5e66c65f-8760-4695-8ae6-5652613358a0
April 29th 2022, 15:07:24.691	"biodata.integration.test.mule@gmail.com" "-" [2022-04-29T15:07:24.691-0400] 1339784 + "POST /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me/importPFB HTTP/1.1" 202 267 "-" "-" "python-requests/2.24.0"
```

the first two requests to check status of the import job are successful - note the 200s buried in these logs, 5th field from the end:
```
April 29th 2022, 15:07:27.156	"biodata.integration.test.mule@gmail.com" "-" [2022-04-29T15:07:27.156-0400] 854952 + "GET /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me/importPFB/24ae6c8f-af21-4609-aa2f-140cf2854916 HTTP/1.1" 200 107 "-" "-" "python-requests/2.24.0"
April 29th 2022, 15:07:30.943	"biodata.integration.test.mule@gmail.com" "-" [2022-04-29T15:07:30.943-0400] 24963569 + "GET /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me/importPFB/24ae6c8f-af21-4609-aa2f-140cf2854916 HTTP/1.1" 200 110 "-" "-" "python-requests/2.24.0"
```

the third request to check status of the import job hits a 401:
```
April 29th 2022, 15:07:59.075	"-" "-" [2022-04-29T15:07:59.075-0400] 2674090 + "GET /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me/importPFB/24ae6c8f-af21-4609-aa2f-140cf2854916 HTTP/1.1" 401 745 "-" "-" "python-requests/2.24.0"
```

after the 401, we see the call to delete the workspace. There's a second call - which is Terra-generated, not from the test code - which tries to get the workspace and receives a 404.
```
April 29th 2022, 15:08:02.759	"biodata.integration.test.mule@gmail.com" "-" [2022-04-29T15:08:02.759-0400] 4835166 + "DELETE /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me HTTP/1.1" 202 86 "-" "-" "python-requests/2.24.0"
April 29th 2022, 15:08:08.171	"pet-100740965239829489699@terra-c8bf33b5.iam.gserviceaccount.com" "-" [2022-04-29T15:08:08.171-0400] 354418 + "GET /api/workspaces/broad-integration-testing/integration_test_pfb_gen3_to_terra_2022_04_29_190714_delete_me?fields=workspace.workspaceId,workspace.googleProject HTTP/1.1" 404 219 "-" "-" "python-requests/2.26.0"
```

From here, the import job is still running, but the workspace no longer exists!

**Comment by DailyDreaming** [comment]
Sorry for the super late reply.  The third request to check status of the import job (that hits a 401) seems odd since it doesn't seem to come from `"biodata.integration.test.mule@gmail.com"` if I understand this correctly?  It looks like a python request, so I assume that the test framework is where it came from, but I don't understand how it could have.

Good sleuthing on the 404 GET fetch post-delete!  I hope fixing that fixes the issue.

I'm going with the assumption that the 401 earlier has not been witnessed occurring outside of this case, in which case it either truly doesn't seem to occur outside of this case or it doesn't seem to affect the ability for the test to complete.

**Comment by DailyDreaming** [comment]
Ah, that makes sense, thank you for the explanation.

The tests should only retry on 500, 502, 503, and 504 errors for nearly all functions (one will retry on 409 to deal with conflicting tests running at the same time), so if a 401 is hit, it should be visible immediately.
